#!/usr/bin/env node

var fs = require('fs')//引入fs模块
var dirName = process.argv[2] // 你传的参数是从第 2 个开始的

fs.mkdirSync("./" + dirName)
process.chdir("./" + dirName)
fs.mkdirSync('css')
fs.mkdirSync('js')

fs.writeFileSync("./index.html", "<!DOCTYPE>\n<title>Hello</title>\n<h1>Hi</h1>")
//fs.writeFileSync("./index.html", "<!DOCTYPE>")
//fs.appendFileSync("./index.html", "<title>Hello</title>");//这种写法后添加的不分行，实际效果好像还行
//fs.appendFileSync("./index.html", "<h1>Hi</h1>");
fs.writeFileSync("css/style.css", "h1{color: red;}")
fs.writeFileSync("./js/main.js", "var string = \"Hello World\"\nalert(string)")//注意双引号前面加\
//fs.writeFileSync("./js/main.js", "var string = \"Hello World\"")
//fs.appendFileSync("./js/main.js", "alert(string)");

process.exit(0)